
package SoapServer.SoapClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SoapDemoImplService", targetNamespace = "http://SoapServer/", wsdlLocation = "http://localhost:9093/ws/demo?wsdl")
public class SoapDemoImplService
    extends Service
{

    private final static URL SOAPDEMOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPDEMOIMPLSERVICE_EXCEPTION;
    private final static QName SOAPDEMOIMPLSERVICE_QNAME = new QName("http://SoapServer/", "SoapDemoImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9093/ws/demo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPDEMOIMPLSERVICE_WSDL_LOCATION = url;
        SOAPDEMOIMPLSERVICE_EXCEPTION = e;
    }

    public SoapDemoImplService() {
        super(__getWsdlLocation(), SOAPDEMOIMPLSERVICE_QNAME);
    }

    public SoapDemoImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPDEMOIMPLSERVICE_QNAME, features);
    }

    public SoapDemoImplService(URL wsdlLocation) {
        super(wsdlLocation, SOAPDEMOIMPLSERVICE_QNAME);
    }

    public SoapDemoImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPDEMOIMPLSERVICE_QNAME, features);
    }

    public SoapDemoImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapDemoImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapDemo
     */
    @WebEndpoint(name = "SoapDemoImplPort")
    public SoapDemo getSoapDemoImplPort() {
        return super.getPort(new QName("http://SoapServer/", "SoapDemoImplPort"), SoapDemo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapDemo
     */
    @WebEndpoint(name = "SoapDemoImplPort")
    public SoapDemo getSoapDemoImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://SoapServer/", "SoapDemoImplPort"), SoapDemo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPDEMOIMPLSERVICE_EXCEPTION!= null) {
            throw SOAPDEMOIMPLSERVICE_EXCEPTION;
        }
        return SOAPDEMOIMPLSERVICE_WSDL_LOCATION;
    }

}
