//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.30 at 03:17:05 PM CET 
//


package pojo.workerspackage;

import data.Worker;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Director" type="{http://www.kuban.org/animals}Director" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Tradesman" type="{http://www.kuban.org/animals}Tradesman" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "director",
    "tradesman"
})
@XmlRootElement(name = "workers")
public class Workers {

    @XmlElement(name = "Director")
    protected List<Director> director;
    @XmlElement(name = "Tradesman")
    protected List<Tradesman> tradesman;

    /**
     * Gets the value of the director property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the director property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDirector().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Director }
     * 
     * 
     */
    public List<Director> getDirector() {
        if (director == null) {
            director = new ArrayList<Director>();
        }
        return this.director;
    }

    /**
     * Gets the value of the tradesman property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tradesman property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTradesman().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tradesman }
     * 
     * 
     */
    public List<Tradesman> getTradesman() {
        if (tradesman == null) {
            tradesman = new ArrayList<Tradesman>();
        }
        return this.tradesman;
    }

    public Workers (List<Director> _directors, List<Tradesman> _tradesman)
    {
        this.director = _directors;
        this.tradesman = _tradesman;
    }

    public Workers()
    {

    }

}
